---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ((image_resource_repository))}

params:
  SECRET: ((task_secret))

run:
  path: sh
  args: ['-c', 'echo SECRET: $SECRET']
