---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  CONCOURSE_IMAGE:
  KUBE_CONFIG:
  RELEASE_NAME:

inputs:
- name: charts
- name: concourse
- name: image-info

run:
  path: concourse/ci/tasks/scripts/k8s-deploy
