---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: full

params:
  GCP_PROJECT:
  GCP_KEY:
  SSH_KEY:
  WORKSPACE: default

inputs:
- name: concourse
- name: linux-rc
  optional: true

outputs:
- name: outputs

run:
  path: concourse/ci/tasks/scripts/terraform-smoke
