---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse

caches:
- path: concourse/node_modules

outputs:
- name: built-concourse

run:
  path: concourse/ci/tasks/scripts/yarn-build
