---
name: concourse

# replace with bosh status --uuid
director_uuid: REPLACE_WITH_UUID

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: REPLACE_WITH_DB_PASSWORD

# replace with an AZ from your account
availability_zone: &az REPLACE_WITH_AVAILABILITY_ZONE

# replace all addresses with your VPC range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        reserved: [10.0.16.2 - 10.0.16.9]
        static:
          - &discovery_static_ip 10.0.16.10
        dns: [10.0.0.2]
        gateway: 10.0.16.1
        cloud_properties:
          security_groups: [REPLACE_WITH_INTERNAL_SECURITY_GROUP_NAME]
          subnet: REPLACE_WITH_INTERNAL_SUBNET

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        basic_auth_username: ~
        basic_auth_password: ~
        postgresql:
          database: *atc-db-name
          role: *atc-db-role

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk_pool: database
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 1
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

disk_pools:
  - name: database
    disk_size: 10240
    cloud_properties:
      type: gp2

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az
      elbs: [REPLACE_WITH_WEB_ELB_NAME]

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.large
      availability_zone: *az

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: *az
    ephemeral_disk:
      size: 30000 # in MB
      type: gp2

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
