---
name: concourse

releases:
  - name: concourse
    url: https://bosh.io/d/github.com/concourse/concourse?v=0.58.0
    sha1: b922b3595d2eedbc300c68a0e406b4a299af3738
  - name: garden-linux
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.275.0
    sha1: 7eaf67ce4ded73bcced92fa310fa82f68667c96a
  - name: bosh-aws-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=7
    sha1: 6545812c1c8245331b8c420f886dafd24b866eed

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=2950
      sha1: 6489bff150d1ecbd12fda30267896f041dd279f0
    cloud_properties:
      instance_type: m3.xlarge
      availability_zone: us-west-1a
      elbs: [concourse]

disk_pools:
  - name: db
    disk_size: 10240
    cloud_properties:
      type: gp2

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        dns: [10.0.0.2]
        gateway: 10.0.16.1
        cloud_properties:
          security_groups: [concourse]
          subnet: SUBNET_ID
  - name: public
    type: vip

jobs:
  - name: concourse
    instances: 1
    resource_pool: concourse
    persistent_disk_pool: db

    templates:
      - {release: concourse, name: atc}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: tsa}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}

    networks:
      - name: public
        static_ips: [ELASTIC_IP]
      - name: concourse
        static_ips: [10.0.16.11]
        default: [dns, gateway]

    properties:
      atc:
        basic_auth_username: &atc_username USERNAME
        basic_auth_password: &atc_password PASSWORD
        postgresql:
          address: RDSADDRESS
          database: DATABASENAME
          role:
            name: RDSUSERNAME
            password: RDSPASSWORD
      tsa:
        forward_host: 127.0.0.1
        atc:
          username: *atc_username
          password: *atc_password
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

cloud_provider:
  template: {name: cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: ELASTIC_IP
    port: 22
    user: vcap
    private_key: PRIVATE_KEY_FILE # Appears to be relative to working dir

  mbus: "https://mbus:mbus-password@ELASTIC_IP:6868"

  properties:
    aws:
      access_key_id: ACCESS_KEY_ID
      secret_access_key: SECRET_ACCESS_KEY
      default_key_name: SSH_KEY_PAIR_NAME
      default_security_groups: [concourse]
      region: us-west-1
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
