---
name: ((deployment_name))

releases:
- name: concourse
  version: ((concourse_version))
- name: garden-runc
  version: ((garden_runc_version))
- name: postgres
  version: latest

instance_groups:
- name: concourse
  instances: 1
  azs: [z1]
  networks:
  - name: ((network_name))
    static_ips: [&web-ip ((web_ip))]
  azs: [z1]
  persistent_disk: 10240
  vm_type: ((vm_type))
  stemcell: xenial
  jobs:
  - release: concourse
    name: atc
    properties:
      log_level: debug

      external_url: http://((web_ip)):8080

      postgresql:
        database: atc
        role:
          name: atc
          password: ((postgres_password))

      main_team:
        auth:
          allow_all_users: true

      add_local_users:
      - test:$2a$10$sDB6AsH2HheOWHILrnHVJOCZq/GYtUYE02ypJJTQBmWJNivYNhP3y

      token_signing_key: ((token_signing_key))

  - release: concourse
    name: tsa
    properties:
      log_level: debug
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys: [((worker_key.public_key))]

  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: atc
          password: ((postgres_password))

  - release: concourse
    name: worker
    properties:
      drain_timeout: 10m
      tsa: {worker_key: ((worker_key))}
      log_level: debug

  - release: concourse
    name: baggageclaim
    properties:
      log_level: debug

  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
