blank_issues_enabled: false

contact_links:
- name: â” Ask for help
  url: https://github.com/concourse/concourse/discussions/new?category=help-support
  about: Ask a question or troubleshoot a problem with Concourse.

- name: ğŸ’¡ Discuss an idea
  url: https://github.com/concourse/concourse/discussions/new?category=ideas
  about: Discuss a workflow that Concourse could better support.
