---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: fec35eca-b15c-44e1-809e-148c7689f341
  sha: !binary |-
    NzQ0MDM2MDU2NTJiNTE5ZDRjYTgzZTVjMzA2NzljZDBlZjQ3MDZiYg==
  size: 2549728
resources/time-resource.tar.gz:
  object_id: 73db0c47-0f5f-4a69-8436-ae3c207d5b9f
  sha: !binary |-
    ZWE4MGUzODJmZGU5N2YyMTg2ZjcxMDBiZjJlNWJkZTY4ZDY3NzMyMQ==
  size: 2518572
resources/semver-resource.tar.gz:
  object_id: 39a437cb-70ae-4e73-9070-f05ac4ea5dc0
  sha: !binary |-
    MzJkNTRlMTI3ZjNjZDMwNWM2ZGE3OTI5ODk4YWIyNmM5NWI1NzQ0ZA==
  size: 8626849
resources/s3-resource.tar.gz:
  object_id: c3108308-41b3-4174-9993-f41671e7ddfd
  sha: !binary |-
    N2Y2ZWU3OTA1ODZkNDZhNTM1NWU0OGJiYWFhMjY0MmQ4ZTFjZmEzZQ==
  size: 8818009
resources/tracker-resource.tar.gz:
  object_id: 0af44815-0984-491b-b029-7d63e091fc1e
  sha: 187656e6605b9dd31b3ead9bf75a9bb11176359d
  size: 11532802
resources/git-resource.tar.gz:
  object_id: 93857bd0-ca1b-40e6-978a-a827c8638a47
  sha: !binary |-
    ZWNhMWU0OGVjYmM1ZmFmMzIxYzYyMjEwOTliOWY5Y2QxMGU5OThkNA==
  size: 9155201
resources/docker-image-resource.tar.gz:
  object_id: 9888948c-936d-41e1-814e-c3989cd0cd0e
  sha: !binary |-
    YmFkY2U4MTg5ZmU3MDQ5NmQ0ODljZjI3ZDFmMjdlNzRjM2JmMTcxNg==
  size: 7951758
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
