---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: a9d03488-fe6c-44c6-a815-d0b76d7afe17
  sha: !binary |-
    MGRlODkyZmM3MzYxZjM2MmFkN2U4NDFmY2E4NTQyZmNmYTA3ODVkMA==
  size: 9647998
resources/time-resource.tar.gz:
  object_id: 860dd863-312c-4a31-8db3-a26f4d92edea
  sha: !binary |-
    NjgwN2QyMjI3ZTJjZmE1MWVjNjFiYWNmMmU3ZDZhN2Q4MzMzNDU1YQ==
  size: 2524039
resources/semver-resource.tar.gz:
  object_id: b9425c53-2e9f-4ca4-9110-0946a1893d3e
  sha: !binary |-
    NjJiOWUxYTM3OGMwMTNhOTk5NTBlYTUwZDVjZTc1MjJmNzhhYzMyZA==
  size: 8644369
resources/s3-resource.tar.gz:
  object_id: fa718a3c-153c-41aa-85c7-de77e8768299
  sha: !binary |-
    MzVkYjMyOTBhZjFkOTBmYmIyNzdlMjcyOWRiZDUyMTgxZmM1ZmM3NA==
  size: 8839419
resources/tracker-resource.tar.gz:
  object_id: f1c43153-4eb9-4590-a7ae-2da9497e0368
  sha: !binary |-
    N2E2YmNiMjg2MjhkZjc3MmUzZmE3NDA4NjE5ZThmMzc4ZDI3YzFkOA==
  size: 11655491
resources/git-resource.tar.gz:
  object_id: 3c86224c-18de-487f-adf2-2c54216c95b6
  sha: !binary |-
    YmRiNGM1YjgxMGExZDhkMjlmN2M2OTE4NGM1MTNhMmVhN2ZlYmRlYw==
  size: 8410592
resources/docker-image-resource.tar.gz:
  object_id: 6f0236d4-7744-4805-a017-e395183475d6
  sha: !binary |-
    NzE3MDJkMjdhMGRmNTRjYjJjZDEyZWI2OWYxOTljMWVlZmQ1YWRkMA==
  size: 8389844
resources/vagrant-cloud-resource.tar.gz:
  object_id: 7a929a84-d9bf-48a9-8116-0f5f09ef4139
  sha: !binary |-
    OGNjZTZiOGU3NzJhNWU4MGYyNTExOTMwNDMwOWQ2Yzc3ZTBjYjg0NA==
  size: 8409188
resources/cf-resource.tar.gz:
  object_id: 4cc3e474-aa62-4371-b4ac-d85348832553
  sha: !binary |-
    N2RkODBiNmJhYzE0NTA4ODEyMzdhMjI0M2I5ZDI0MjU3NmU1YzAyMA==
  size: 13379855
resources/github-release-resource.tar.gz:
  object_id: 704f07cb-2425-41ed-bb7f-c0d7402d5a04
  sha: !binary |-
    YmNjMWQxZmI4NWQwM2RjNTI3ZGQ1M2ZlMDQ5NWVhODlmNzBmOWRkNg==
  size: 8841286
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 6709e19c-369b-4d0d-bf25-f7d655024c9f
  sha: !binary |-
    Y2E0OGFlMmRlM2EzYTQ2YzU4N2ZjNWNhZGYzYWY4Yzc1NGMyYzI0OA==
  size: 8407988
resources/bosh-io-release-resource.tar.gz:
  object_id: 8b247e46-8f37-4656-bda8-9fd65d05df98
  sha: !binary |-
    OTcyNThjMzAzOTVlMGQ4Y2YxYTdkMzZhNzE1MjMwZDBhZTg0MDVjYQ==
  size: 8409411
resources/bosh-deployment-resource.tar.gz:
  object_id: 0f2f54c3-aba1-417d-9dc0-9ecc00937c68
  sha: !binary |-
    NWJiNDQ3NjA1MWY2OGNhZWI3NGVkYTIzMTYxZmYwMWM5YzY5M2UxNg==
  size: 22174342
