btrfs/btrfs-tools.tar.gz:
  size: 3016424
  object_id: b201ed45-7a52-4c32-b213-d666b60b1954
  sha: abdf982cee43881659adc24c3e347b37b65f8530
golang/golang-linux-amd64.tar.gz:
  size: 89803580
  object_id: 027537dd-578c-4a55-4efe-85c1257766b7
  sha: a93fe8fc245e3554f956bc823f30ef4eb23c2068
postgresql/postgresql-9.3.4.tar.gz:
  size: 21865589
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
resources/archive-resource.tar.gz:
  size: 7617771
  object_id: b5bc751b-0855-48ce-7131-49e57a98303a
  sha: 7f99a0635476bf2d6311a74af9fb75b7f3f5e7b7
resources/bosh-deployment-resource.tar.gz:
  size: 13179543
  object_id: 46b8d9c8-15cf-4787-664b-600d59ffba5b
  sha: 814abd117bc9932ca86c8e08b0a05fe76b86f567
resources/bosh-io-release-resource.tar.gz:
  size: 5029014
  object_id: f4550d3f-8085-4036-4535-8f2dc377895b
  sha: 1ffb83a892ff575505b9f142a2868fb5e544c866
resources/bosh-io-stemcell-resource.tar.gz:
  size: 7708925
  object_id: cd129cdc-a525-4baa-7f17-64c75c8bac72
  sha: cb363f0c4765227fcec2f485452842f787c02e1e
resources/cf-resource.tar.gz:
  size: 18118209
  object_id: b95699d5-7c4e-45b7-6dd3-d2a9cb331c2a
  sha: f31bd03ab7c6603ad2331a0429c68c7bdad398cb
resources/docker-image-resource.tar.gz:
  size: 41031168
  object_id: c25ef3f5-9dbb-497c-4aaf-34743ba20912
  sha: 2eb80cf0bbfcfbb257720675b30168844e2a5dde
resources/git-resource.tar.gz:
  size: 15435054
  object_id: 42c126d8-2925-4032-65f0-b84bd969cd5a
  sha: 984497affb6241e41ef8199580dc40486d4a2d66
resources/github-release-resource.tar.gz:
  size: 9970091
  object_id: 655b7131-2fa2-4068-52f0-901dc54b5265
  sha: 470f023400d85e136199244be736621a8942c634
resources/hg-resource.tar.gz:
  size: 14892388
  object_id: 7c737e3d-7b7c-41b7-4dae-ddd685434386
  sha: 4c9b239676b6a03314ce87f726f997480d18221f
resources/pool-resource.tar.gz:
  size: 13154191
  object_id: de1947a2-25a2-43b9-7ce8-6e62c4dbfe95
  sha: 8091e1e0c5cc65e22dbc473d9405836d0d701117
resources/s3-resource.tar.gz:
  size: 13654041
  object_id: 91e29c19-936d-4699-5aab-7bd2a165edfa
  sha: 22b24634662939b78ed6b1521878828c55d9603b
resources/semver-resource.tar.gz:
  size: 18355848
  object_id: 686fbb7f-e668-420b-4fd0-96d83e56b297
  sha: bbf8e44bba7694b505a47f46a45f8a515d2debdf
resources/time-resource.tar.gz:
  size: 6103267
  object_id: f4fe071d-5cd6-4866-7738-a7cb64c4a59d
  sha: 035c6cce948f23afa05fb8dfd134c11e6d99c621
resources/tracker-resource.tar.gz:
  size: 15712643
  object_id: f46b5ca2-3690-4285-42b7-76d31c0adef8
  sha: 912f2c295a2f7448724a0d97977a4eb3517245a5
resources/vagrant-cloud-resource.tar.gz:
  size: 5029085
  object_id: 84b98573-9f1f-41a3-6e5a-3a15c3c508d5
  sha: 8d92c205e722ef5bf45f2818f35a14fa8ed69191
