btrfs/btrfs-tools.tar.gz:
  size: 3016424
  object_id: b201ed45-7a52-4c32-b213-d666b60b1954
  sha: abdf982cee43881659adc24c3e347b37b65f8530
golang/golang-linux-amd64.tar.gz:
  size: 84021919
  object_id: b3dcb3ef-25f2-4137-4711-0ca227864cac
  sha: 2e5baf03d1590e048c84d1d5b4b6f2540efaaea1
postgresql/postgresql-9.3.4.tar.gz:
  size: 21865589
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
resources/archive-resource.tar.gz:
  size: 7500909
  object_id: 77355aed-61a8-4036-62f4-06ac12656a49
  sha: 4f20ef32e458dc0e1fe173c1d4c3dff4e1f03be2
resources/bosh-deployment-resource.tar.gz:
  size: 13172510
  object_id: 8c5a8706-888c-477b-6c53-bf56186766f7
  sha: fe37e1ce6d9c8f81c812faac0ea6b1ff23e188a6
resources/bosh-io-release-resource.tar.gz:
  size: 5030142
  object_id: 92a05c45-0ca5-4bde-6d46-b82531bca4f1
  sha: 838dd4f1a838de15e87f43cf9c7a21628653a92a
resources/bosh-io-stemcell-resource.tar.gz:
  size: 7702462
  object_id: b6c0c989-fa58-405a-5df0-0b91660c12cd
  sha: c73c05f795604e7a290c49d3510deff93a3bdf33
resources/cf-resource.tar.gz:
  size: 18041343
  object_id: 5ccd1bf1-52f1-47b4-460c-d852966e3a1e
  sha: a1918b5307d39ec57b0ae39252ded7917bbdea5e
resources/docker-image-resource.tar.gz:
  size: 42121509
  object_id: dd90a98d-fe51-4b6d-48a1-d4954944c70b
  sha: a9e073a2711f427a8a4b281bec32c6cdf58aed55
resources/git-resource.tar.gz:
  size: 15780093
  object_id: 7f196ca1-987e-4a74-4e78-751ddfc4d73b
  sha: 6d0b24ebe74828b2e7112c78738653e798e650e7
resources/github-release-resource.tar.gz:
  size: 9968960
  object_id: dfe9d956-6a5f-403e-7783-3c62ba03d487
  sha: 89532760e73b363f22f9be178810b2b50b64aa81
resources/hg-resource.tar.gz:
  size: 14892628
  object_id: 2ad2af7c-f6df-4e96-4944-963fc38a84d9
  sha: f376d2035e6e45e222e0769678fc4f8061e6d2b2
resources/pool-resource.tar.gz:
  size: 13154099
  object_id: e10a3f9b-10ad-44ce-4557-05f24fa76dbc
  sha: 5637707e8c2e8da19a610387749bc9adbd77a82d
resources/s3-resource.tar.gz:
  size: 11723121
  object_id: de32566e-3d7b-4344-4bec-fd87d37af633
  sha: a2d258681b74382c546a03bf2b3139941c82d848
resources/semver-resource.tar.gz:
  size: 18355017
  object_id: 7b3a99ac-5958-4569-7f0d-e80983befe48
  sha: c7657e6ea66592b07ba9780fad4f9eec0b849eea
resources/time-resource.tar.gz:
  size: 6102305
  object_id: 12f6591a-db01-4733-4c6d-44c41c20c6b1
  sha: 5ec40a8c095844f31edaaabe1884b9a8854b8036
resources/tracker-resource.tar.gz:
  size: 15712237
  object_id: a506dfcb-a56b-4152-4bed-f494d9a51b34
  sha: d960035a90da6ff267418740fde7441d7b71dda2
resources/vagrant-cloud-resource.tar.gz:
  size: 5029090
  object_id: dcc98163-488c-4f7b-633b-6708491ce38d
  sha: 7509ab40e9b91bc2ab22d5b08fa1b5287917d567
