---
postgresql/postgresql-9.3.4.tar.gz:
  size: 21865589
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
resources/archive-resource.tar.gz:
  object_id: a1e21959-2754-4abc-ba3f-0000f9576fc3
  sha: c10966746aafed10f63e200a172a7e260ce71b77
  size: 9625496
resources/bosh-deployment-resource.tar.gz:
  object_id: 6169e555-200d-4aa0-a1f2-9af19a104302
  sha: c9331a885416ccdff72a10a0753ee6fc07e8dbc4
  size: 14958458
resources/bosh-io-release-resource.tar.gz:
  object_id: 7dd9de64-7769-4fd4-aedf-8ea202fb55bb
  sha: 4a11492bc3c28e400d381baa0a2b7a6d289542a5
  size: 6839439
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: df0761e9-0a17-4c7a-afed-95309e5f14d1
  sha: aa724259d8c82f0f6f6d82d31fd97d13678d15a7
  size: 6839433
resources/cf-resource.tar.gz:
  object_id: a4bb6f35-417d-43d5-a573-a0812aa53db8
  sha: 64450c58fc931945829ea04b5906863c98a7c0d9
  size: 20668909
resources/docker-image-resource.tar.gz:
  object_id: 987e887b-f84d-4fdc-b1ee-21451909f041
  sha: 6ce7044e3d5eaff489b66375345d67e41f0b1d8f
  size: 34338761
resources/git-resource.tar.gz:
  object_id: 92b44b8d-00c8-4263-9e39-b6d4883d4288
  sha: 27aefcdd71f71ac087920d898bf33068c062bf2e
  size: 13913637
resources/github-release-resource.tar.gz:
  object_id: 0137ffba-d282-44f9-a582-a2b516d82518
  sha: e8dc8f84f6949a552242de1bdc5586f712fa9000
  size: 14016450
resources/pool-resource.tar.gz:
  object_id: 27631a92-c9e4-436b-b5f2-cec38eeab87d
  sha: d3bddbfc85a30f9ffad688fa782335aa8ce1f6b5
  size: 11285676
resources/s3-resource.tar.gz:
  object_id: 5ae5674a-caad-45ef-8640-dfffbf3887af
  sha: 0ac3acd4c2e3aa8131aa965256f4be962eafd961
  size: 15420055
resources/semver-resource.tar.gz:
  object_id: 724eaf4b-0786-4504-9aa0-ad73c86f3fa3
  sha: 0335e1c66b59c1ad34cd67381dd480462ff24678
  size: 18270313
resources/time-resource.tar.gz:
  object_id: 9381b535-c235-4842-affe-d9357bff4f22
  sha: 4954e51dc5b01b86f6774136dbd6faf1ef185db2
  size: 8132208
resources/tracker-resource.tar.gz:
  object_id: cbc1e02d-8b1b-4a2b-b099-a14777d26411
  sha: 093232947cea882704f10653813f61f12b6aed27
  size: 14580009
resources/vagrant-cloud-resource.tar.gz:
  object_id: d8e6be95-6198-438e-a156-64cd73c6e81c
  sha: 2dfa93665876f224dec7bcfb1c5772037c3cdc08
  size: 6840986
golang_1.6/go1.6.1.linux-amd64.tar.gz:
  object_id: 980f2086-2872-4159-a73f-77ea2905d21b
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
btrfs/btrfs-tools.tar.gz:
  object_id: b201ed45-7a52-4c32-b213-d666b60b1954
  sha: abdf982cee43881659adc24c3e347b37b65f8530
  size: 3016424
resources/hg-resource.tar.gz:
  object_id: e4db8e88-62d6-4e85-be81-c619783adfdb
  sha: 389acc1c665f3b1a03cb75d0cbbcddb62772f2b4
  size: 16554914
