btrfs/btrfs-tools-4.4.tar.gz:
  size: 3062268
  object_id: 9c8e0f55-d9e0-4a6a-51f3-1b175f3b2551
  sha: 94279d010ebd4829396af9212f9c1e73e75d914e
golang/go1.11.5.linux-amd64.tar.gz:
  size: 140132627
  object_id: a47afec8-0df2-4fa7-5abd-ae9cd4b72adc
  sha: b951c39500c4c85f57b7549ebc87281816d28f59
resources/bosh-io-release-resource-b7d0e93.tar.gz:
  size: 4740520
  object_id: f3994c11-24fb-4fdb-6cbc-3b159947509a
  sha: 71129641352376a1b73cc87ed9c88d11dc85a8ae
resources/bosh-io-stemcell-resource-c144c16.tar.gz:
  size: 10035101
  object_id: 09facf25-b081-4faa-712f-51de760d04d7
  sha: 6d8f703d1007c03c17fb7c8dee399c6293fd7d2b
resources/cf-resource-32d7a1d.tar.gz:
  size: 21093427
  object_id: 6f45f9d6-9900-40e6-5b30-88bb660399f6
  sha: 6a56b7ba92571039efbf20db47ae5031a3abbce8
resources/docker-image-resource-6ceefc0.tar.gz:
  size: 58244533
  object_id: 43cd9c87-1d07-460b-5fbe-546eaeb1436c
  sha: 9b0e9f2329374b2b8b5eba9babed9a7155b8a1b6
resources/git-resource-23285aa.tar.gz:
  size: 77710016
  object_id: 9d674bab-06f9-4161-550e-34ef062cb9f3
  sha: 8463018ac0221f67fdcdbef577665f91a5e6b91c
resources/github-release-resource-650d95f.tar.gz:
  size: 12739675
  object_id: 03350fd9-ed38-4223-68d0-eaf9ebe3e080
  sha: b8f039e0d2e4504f9a93e928bf4cfb86d772b502
resources/hg-resource-64a2436.tar.gz:
  size: 29210151
  object_id: 7a2c9943-fe83-4bf2-518a-a02ba889ed2b
  sha: 61c249180391dc134f3eae0451ece8791a092223
resources/pool-resource-06598ca.tar.gz:
  size: 25925573
  object_id: cd6e60fe-ad2c-49c5-41d7-e065ba14784e
  sha: 42c6515067293be31a04d1aa06db22f5755ca3e0
resources/registry-image-resource-19f7e0e.tar.gz:
  size: 12925903
  object_id: 70152098-4043-418d-7970-7782851f188a
  sha: d05008ef052b6d8e336f0a035d4e250f68fa36eb
resources/s3-resource-2bbfea5.tar.gz:
  size: 14568632
  object_id: 24911fa3-46a9-4600-442e-37581b787f00
  sha: 817afad8bfa7719f9c35bbf178f2db9935754b98
resources/semver-resource-55858c5.tar.gz:
  size: 24956366
  object_id: 6f72219e-a6f0-42f8-4fac-bf3359bc729f
  sha: 3cbc2e0d26bad27b54f2842baf7f8b7ed442a1f3
resources/time-resource-d3c2c98.tar.gz:
  size: 7705958
  object_id: 19e8e389-3652-4e70-6c2f-fd56ffa897b7
  sha: f6064767212cf53760fa581c3c17e9f76e6dbd00
resources/tracker-resource-b18b7a9.tar.gz:
  size: 16571291
  object_id: aef9c91c-5fcb-4e63-7eab-a7e9cd17ec32
  sha: 0eea89deed2b792aba163172619f4cf99093928d
