---
postgresql/postgresql-9.3.4.tar.gz:
  size: 21865589
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
resources/archive-resource.tar.gz:
  object_id: 94fed467-a119-4a52-98ad-25e9e72fa362
  sha: 24bbfda1e5b0fd1b9e956309c91d06435f9a4128
  size: 9625906
resources/bosh-deployment-resource.tar.gz:
  object_id: e4a8f1a4-1f84-4194-b9c4-2f3ada47f6f0
  sha: 8c0cb65f2791ca7d3a23d3e55c52367d90cfa05e
  size: 14957762
resources/bosh-io-release-resource.tar.gz:
  object_id: 925bd032-2086-4216-a5d2-66417831181f
  sha: b0a06387ef3329f7fbd25eb086e698392f1f8adc
  size: 6839151
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 790a840c-0613-4e4b-906f-5ff355477593
  sha: f58b036071a080e598dfcc5f7f8ca28ff985d35a
  size: 6840281
resources/cf-resource.tar.gz:
  object_id: 9e33dd04-8790-49e3-8263-0b53914e2ffb
  sha: 6f5a2ec6b7381ada1d82e8d0722e19acb1cfb39d
  size: 20583023
resources/docker-image-resource.tar.gz:
  object_id: 0c4e0470-db7f-4c25-95c0-86d8cd029398
  sha: f3303fc57f3579bbaa6347d1c554c591bc7c634d
  size: 30801682
resources/git-resource.tar.gz:
  object_id: 7fc98f07-1e28-464c-bdfa-6f4604c84e68
  sha: 7802c47fc149236a33cae00b52574a4a94843aa6
  size: 13914012
resources/github-release-resource.tar.gz:
  object_id: 30392557-6fe3-47f9-97f9-c5ac116bc280
  sha: 6a500e3fdc0e61b83ef19cd3d63126a341d04b50
  size: 13824334
resources/pool-resource.tar.gz:
  object_id: e45d3294-47a9-446e-9cfd-f5ff1f4c6a2d
  sha: 9e647c929ab637f941073a81531ad05f78402c6e
  size: 11286382
resources/s3-resource.tar.gz:
  object_id: b874c6aa-7fbb-4254-bc59-951283fed69a
  sha: bb7f1f930b34400193087ac26987ed2e77fdca9a
  size: 15418586
resources/semver-resource.tar.gz:
  object_id: b1c3d75b-96bd-45a3-afdd-14f5a154bbbc
  sha: 12577c72c5095905ec30939a47d2fc432dd2a307
  size: 18270765
resources/time-resource.tar.gz:
  object_id: 68dd9af2-142b-4c50-b3f9-f30f6bdef312
  sha: 9413fd43ad9c50d99aa9526b5876319edc62c834
  size: 8130359
resources/tracker-resource.tar.gz:
  object_id: 7285bdd5-2ba4-4b5b-819a-4d810a612e1d
  sha: faeea15a234808ac11938b784f9c59d449aba137
  size: 14580895
resources/vagrant-cloud-resource.tar.gz:
  object_id: 4284090f-2d02-438c-bd94-a13afd0333a0
  sha: da88838f245a2c8501e0facc49955746d1ca1041
  size: 6841214
golang_1.6/go1.6.1.linux-amd64.tar.gz:
  object_id: 980f2086-2872-4159-a73f-77ea2905d21b
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
btrfs/btrfs-tools.tar.gz:
  object_id: b201ed45-7a52-4c32-b213-d666b60b1954
  sha: abdf982cee43881659adc24c3e347b37b65f8530
  size: 3016424
resources/hg-resource.tar.gz:
  object_id: 00ce0640-569c-4881-b476-2e1ab96ed4a1
  sha: 34f0747e21947b73d1597e2d848a215c00ca98a4
  size: 16555857
